### ISSUE TITLE
Improve CI jobs

### ISSUE THREAD

**Issue by julienrbrt** [cosmos/gogoproto#11]
Currently, we have no job that ensures that all the commands are built correctly.
- Setup `make buildserverall`

**Comment by marbar3778** [comment]
does this need a review? saw it in the board

**Comment by julienrbrt** [comment]
I have put it back in progress. I will finish that soon.

**Comment by julienrbrt** [comment]
It is ready btw: https://github.com/cosmos/gogoproto/pull/14
