### ISSUE TITLE
New warnings with v1.4.9

### ISSUE THREAD

**Issue by alpe** [cosmos/gogoproto#66]
The following warnings showed up on any wasmd CLI command. This happened after bumping the version from v1.4.8 to v1.4.9:
```
WARNING: proto: file "google/protobuf/any.proto" already registered
WARNING: proto: file name query.proto does not start with expected testdata/; please make sure your folder structure matches the proto files fully-qualified names
WARNING: proto: file name testdata.proto does not start with expected testdata/; please make sure your folder structure matches the proto files fully-qualified names
WARNING: proto: file name tx.proto does not start with expected testdata/; please make sure your folder structure matches the proto files fully-qualified names
WARNING: proto: file name unknonwnproto.proto does not start with expected testdata/; please make sure your folder structure matches the proto files fully-qualified names
```
see https://app.circleci.com/pipelines/github/CosmWasm/wasmd/3516/workflows/b257588d-5951-4476-80b2-ceefbc2cd20f/jobs/14618

These warnings are confusing and were breaking CI scripts that expect a concrete output

**Comment by julienrbrt** [comment]
ref: https://github.com/cosmos/cosmos-sdk/pull/16030, https://github.com/cosmos/cosmos-sdk/pull/16083 and https://github.com/cosmos/cosmos-sdk/issues/16089

**Comment by julienrbrt** [comment]
The warning will completely disappear with Cosmos SDK v0.47.3 and cosmos/gogoproto v1.4.10.
When not Cosmos SDK v0.47.0-v0.47.2, best to stay on a version < 1.4.9.
